<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPages/Admin.Master" AutoEventWireup="true" CodeBehind="FeedBacks.aspx.cs" Inherits="delete2.FeedBacks" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
<style type="text/css">
        .style1
        {
            width: 100%;
        }
        .style3
        {
            width: 128px;
        }
        .style4
        {
            width: 58px;
        }
        .style6
        {
            width: 86px;
        }
        .style7
        {
            width: 66px;
        }
        .style8
        {
            width: 7px;
        }
        .style9
        {
            font-size:15;
            font-weight:bold;    
        }
        .style10
        {
            width: 188px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

      <div id='divsearch'>
        <asp:Label ID="Label1" CssClass="style9" runat="server" Text="Filter By" ></asp:Label>
    
        <table class="style1">
            <tr>
                <td class="style6">
                    <asp:Label ID="lblbyFeedbackid" runat="server" Text="Feedback ID"></asp:Label>
                </td>
                <td class="style3">
                    <asp:TextBox ID="txtFeedback" runat="server" Width="185px"></asp:TextBox>
                </td>
                <td class="style4">
                    <asp:Button ID="btnFeedback" runat="server" Text="O" Height="21px" Width="16px" onclick="btnFeedback_Click" 
                         /></td>
                <td class="style7">
                    <asp:Label ID="lblbyUser" runat="server" Text="User ID"></asp:Label>
                </td>
                <td class="style10">
                    <asp:TextBox ID="txtUser" runat="server" Width="185px"></asp:TextBox>
                </td>
                <td class="style8">
                    <asp:Button ID="btnUser" runat="server" Text="O" Height="21px" Width="16px" 
                       style="margin-left: 0px" onclick="btnUser_Click" /></td>
                
            </tr>
            <tr>
                <td>
                    <asp:DropDownList ID="DropDownList1" runat="server">
                        <asp:ListItem Value="1">On</asp:ListItem>
                        <asp:ListItem Value="2">Before</asp:ListItem>
                        <asp:ListItem Value="3">After</asp:ListItem>
                    </asp:DropDownList>
                </td>
                <td>
                    <asp:Calendar ID="Calendar1" runat="server" 
                        onselectionchanged="Calendar1_SelectionChanged"></asp:Calendar>
                </td>
                
            </tr>
        </table> 
    </div>


        <br />
        <asp:Label ID="Label4" CssClass="style9" runat="server"  >No Entry Found</asp:Label>
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
          AutoGenerateDeleteButton="True">
            <AlternatingRowStyle BackColor="#999999" />
        </asp:GridView>
</asp:Content>
